services:
  html-router-apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: html-router-apache
    ports:
      - "5000:80"
    volumes:
      - ./public:/var/www/html
      - ./router.php:/var/www/html/index.php
