services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: html-router-nginx
    volumes:
      - ./public:/var/www/html
      - ./router.php:/var/www/html/index.php

  nginx:
    image: nginx:alpine
    ports:
      - "5001:80"
    volumes:
      - ./public:/var/www/html
      - ./router.php:/var/www/html/index.php
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
